"""Terminal, Markdown and JSON output."""

from __future__ import annotations

import dataclasses
import json
from collections import Counter
from datetime import UTC, datetime

from .grade import PRIORITY_MEANING, Grade
from .scan import PQ_ENUM, ScanResult

GRADE_COLORS = {"A+": "92", "A": "92", "B": "93", "C": "33", "D": "91", "F": "91", "ERR": "90"}


class Painter:
    def __init__(self, color: bool):
        self.color = color

    def __call__(self, text: str, code: str) -> str:
        return f"\033[{code}m{text}\033[0m" if self.color else text


def _mark(ok: bool | None, p: Painter) -> str:
    if ok is None:
        return p("?", "90")
    return p("yes", "92") if ok else p("no", "91")


def _cert_line(r: ScanResult) -> str:
    c = r.cert
    if c is None:
        return "not read"
    key = f"{c.key_type} {c.key_bits}" if c.key_bits else (c.key_type or "?")
    trust = {True: "trusted", False: "UNTRUSTED", None: "trust unknown"}[c.trusted]
    return f"{key}, {c.sig_alg}, issuer {c.issuer}, {c.days_left} days left, {trust}"


def render_terminal(results: list[tuple[ScanResult, Grade]], color: bool = True) -> str:
    p = Painter(color)
    out = []
    for r, g in results:
        letter = p(f" {g.letter:^3} ", f"1;{GRADE_COLORS.get(g.letter, '0')};7")
        out.append(f"\n{letter}  {p(r.target.label, '1')}")
        if not r.reachable:
            out.append(f"       {g.findings[0].detail}")
            continue
        versions = "  ".join(f"{k.removeprefix('TLSv')} {_mark(val, p)}" for k, val in r.versions.items())
        out.append(f"       TLS        {versions}")
        b = r.browser
        chosen = b.group_name if b and b.status == "selected" else (b.alert_name or b.status if b else "?")
        out.append(f"       browsers   {chosen}")
        pq = "  ".join(f"{n} {_mark(r.pq_groups.get(n), p)}" for n in PQ_ENUM)
        out.append(f"       PQ groups  {pq}")
        out.append(f"       cert       {_cert_line(r)}")
        for s in g.strengths:
            out.append(f"       {p('+', '92')} {s}")
        for f in g.findings:
            code = {"P0": "91", "P1": "93", "P2": "36", "P3": "90"}[f.priority]
            out.append(f"       {p(f.priority, code)} {f.title}")
    if len(results) > 1:
        out.append("\n" + summary_line(results))
    return "\n".join(out) + "\n"


def summary_line(results: list[tuple[ScanResult, Grade]]) -> str:
    grades = Counter(g.letter for _, g in results)
    reachable = [r for r, _ in results if r.reachable]
    pq = sum(1 for r in reachable if r.browser_pq)
    t13 = sum(1 for r in reachable if r.tls13)
    n = len(reachable) or 1
    dist = ", ".join(f"{k}: {grades[k]}" for k in ["A+", "A", "B", "C", "D", "F", "ERR"] if grades[k])
    return (
        f"{len(results)} targets, {len(reachable)} reachable. "
        f"TLS 1.3: {t13}/{len(reachable)} ({100 * t13 / n:.0f}%). "
        f"Hybrid PQ for browsers: {pq}/{len(reachable)} ({100 * pq / n:.0f}%). Grades: {dist}."
    )


def render_markdown(results: list[tuple[ScanResult, Grade]]) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Post-quantum TLS readiness report",
        "",
        f"Generated by pqready on {now}.",
        "",
        summary_line(results),
        "",
        "| Target | Grade | TLS 1.3 | Browser key exchange | PQ groups accepted | Certificate |",
        "|---|---|---|---|---|---|",
    ]
    for r, g in results:
        if not r.reachable:
            lines.append(f"| {r.target.label} | {g.letter} | | | | unreachable |")
            continue
        b = r.browser
        chosen = b.group_name if b and b.status == "selected" else "none"
        pq = ", ".join(n for n, ok in r.pq_groups.items() if ok) or "none"
        cert = f"{r.cert.sig_alg}, {r.cert.days_left}d left" if r.cert else "not read"
        lines.append(f"| {r.target.label} | **{g.letter}** | {'yes' if r.tls13 else 'no'} | {chosen} | {pq} | {cert} |")

    lines += ["", "## Migration priorities", ""]
    for prio, meaning in PRIORITY_MEANING.items():
        items = [(r, f) for r, g in results for f in g.findings if f.priority == prio]
        if not items:
            continue
        lines += [f"### {prio}: {meaning}", ""]
        for r, f in items:
            lines.append(f"- **{r.target.label}**: {f.title}. {f.detail}")
        lines.append("")
    return "\n".join(lines)


def _jsonable(obj):
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(type(obj))


def render_json(results: list[tuple[ScanResult, Grade]]) -> str:
    payload = []
    for r, g in results:
        item = dataclasses.asdict(r)
        item["tls13"] = r.tls13
        item["browser_pq"] = r.browser_pq
        item["grade"] = dataclasses.asdict(g)
        payload.append(item)
    return json.dumps(payload, indent=2, default=_jsonable)
